version: '3'
services:
    web:
        restart: always
        build: ./app
        working_dir: /app
        volumes:
            - ./app:/app
        ports:
            - "5000:5000"
        # command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app
        command: /usr/local/bin/python app.py
    # nginx:
    #     restart: always
    #     image: nginx
    #     volumes:
    #         - ./nginx/conf.d:/etc/nginx/conf.d
    #         - ./static:/static
    #     links:
    #         - web:web
    #     ports:
    #         - "80:8000"
