version: '3'
services:
    web:
        restart: always
        build: ./app
        volumes:
            - mydatabase:/usr/src/app/db
        expose:
            - "8000"
        command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app
    nginx:
        restart: always
        build: ./nginx
        links:
            - web:web
        ports:
            - "80:80"
volumes:
    mydatabase:
